version: '3.8'

services:
  web:
    image: ghcr.io/azuracast/azuracast:latest
    volumes:
      - azuracast_station_data:/var/azuracast/stations
      - azuracast_data:/var/azuracast
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "2022:2022"     # SFTP
      - "8000:8000"     # Icecast/SHOUTcast
    restart: unless-stopped
    networks:
      - azuracast_internal

volumes:
  azuracast_data:
  azuracast_station_data:

networks:
  azuracast_internal:
